name: test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'npm'

      - run: npm ci
      - run: npm test

  end-to-end:
    name: End-to-End
    runs-on: ubuntu-latest
    # do not run from forks, as forks don’t have access to repository secrets
    if: github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: ./ # Uses the action in the root directory
        id: prompt
        with:
          prompt: 'Why is the sky blue?'
          api-key: ${{ secrets.AI_GATEWAY_API_KEY }}
      - uses: ./ # Uses the action in the root directory
        id: prompt-with-structured-output
        with:
          prompt: 'What is the capital of France?'
          api-key: ${{ secrets.AI_GATEWAY_API_KEY }}
          schema: |
            {
              "type": "object",
              "properties": {
                "capital": { "type": "string" }
              }
            }
      - run: echo "${{ steps.prompt.outputs.text }}"
      - run: echo "${{ steps.prompt-with-structured-output.outputs.json }}"
